// <auto-generated />
using ClinicBooking.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ClinicBooking.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260507000000_SeedCaLamViecHomNay")]
    partial class SeedCaLamViecHomNay
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Design-time only — not used at runtime.
        }
    }
}
