// <auto-generated />
using System;
using ClinicBooking.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClinicBooking.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260509021305_UpdateSeedCoDau")]
    partial class UpdateSeedCoDau
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClinicBooking.Domain.Entities.BacSi", b =>
                {
                    b.Property<int>("IdBacSi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBacSi"));

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BangCap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdChuyenKhoa")
                        .HasColumnType("int");

                    b.Property<int>("IdTaiKhoan")
                        .HasColumnType("int");

                    b.Property<string>("LoaiHopDong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NamKinhNghiem")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TieuSu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdBacSi");

                    b.HasIndex("IdChuyenKhoa");

                    b.HasIndex("IdTaiKhoan")
                        .IsUnique();

                    b.ToTable("BacSi");

                    b.HasData(
                        new
                        {
                            IdBacSi = 2001,
                            AnhDaiDien = "https://via.placeholder.com/150",
                            BangCap = "Bac Si",
                            HoTen = "Dr. Nguyen Van A",
                            IdChuyenKhoa = 1,
                            IdTaiKhoan = 2002,
                            LoaiHopDong = "NoiTru",
                            NamKinhNghiem = 10,
                            NgayTao = new DateTime(2026, 4, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            TieuSu = "Bac si chuyen khoa tim mach",
                            TrangThai = "DangLam"
                        });
                });

            modelBuilder.Entity("ClinicBooking.Domain.Entities.BenhNhan", b =>
                {
                    b.Property<int>("IdBenhNhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBenhNhan"));

                    b.Property<bool>("BiHanChe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Cccd")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdTaiKhoan")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayHetHanChe")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLanHuyMuon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("IdBenhNhan");

                    b.HasIndex("Cccd")
                        .IsUnique()
                        .HasFilter("[Cccd] IS NOT NULL");

                    b.HasIndex("IdTaiKhoan")
                        .IsUnique();

                    b.ToTable("BenhNhan");

                    b.HasData(
                        new
                        {
                            IdBenhNhan = 2001,
                            BiHanChe = false,
                            Cccd = "123456789012",
                            DiaChi = "123 Duong ABC, TP. HCM",
                            GioiTinh = "Nu",
                            HoTen = "Tran Thi B",
                            IdTaiKhoan = 2001,
                            NgaySinh = new DateOnly(1990, 5, 15),
                            NgayTao = new DateTime(2026, 4, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            SoLanHuyMuon = 0
                        });
                });

            modelBuilder.Entity("ClinicBooking.Domain.Entities.CaLamViec", b =>
                {
                    b.Property<int>("IdCaLamViec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCaLamViec"));

                    b.Property<TimeOnly>("GioBatDau")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("GioKetThuc")
                        .HasColumnType("time");

                    b.Property<int?>("IdAdminDuyet")
                        .HasColumnType("int");

                    b.Property<int>("IdBacSi")
                        .HasColumnType("int");

                    b.Property<int?>("IdBacSiYeuCau")
                        .HasColumnType("int");

                    b.Property<int>("IdChuyenKhoa")
                        .HasColumnType("int");

                    b.Property<int>("IdDinhNghiaCa")
                        .HasColumnType("int");

                    b.Property<int>("IdPhong")
                        .HasColumnType("int");

                    b.Property<string>("LyDoTuChoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayDuyet")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("NgayLamViec")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguonTaoCa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoSlotDaDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("SoSlotToiDa")
                        .HasColumnType("int");

                    b.Property<int>("ThoiGianSlot")
                        .HasColumnType("int");

                    b.Property<string>("TrangThaiDuyet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCaLamViec");

                    b.HasIndex("IdAdminDuyet");

                    b.HasIndex("IdBacSi");

                    b.HasIndex("IdBacSiYeuCau");

                    b.HasIndex("IdChuyenKhoa");

                    b.HasIndex("IdDinhNghiaCa");

                    b.HasIndex("IdPhong");

                    b.ToTable("CaLamViec");

                    b.HasData(
                        new
                        {
                            IdCaLamViec = 3001,
                            GioBatDau = new TimeOnly(7, 0, 0),
                            GioKetThuc = new TimeOnly(12, 0, 0),
                            IdAdminDuyet = 2004,
                            IdBacSi = 2001,
                            IdChuyenKhoa = 1,
                            IdDinhNghiaCa = 1,
                            IdPhong = 1,
                            NgayDuyet = new DateTime(2026, 4, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            NgayLamViec = new DateOnly(2026, 4, 24),
                            NgayTao = new DateTime(2026, 4, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            NguonTaoCa = "TuDong",
                            SoSlotDaDat = 0,
                            SoSlotToiDa = 15,
                            ThoiGianSlot = 20,
                            TrangThaiDuyet = "DaDuyet"
                        },
                        new
                        {
                            IdCaLamViec = 3002,
                            GioBatDau = new TimeOnly(13, 0, 0),
                            GioKetThuc = new TimeOnly(17, 0, 0),
                            IdAdminDuyet = 2004,
                            IdBacSi = 2001,
                            IdChuyenKhoa = 1,
                            IdDinhNghiaCa = 2,
                            IdPhong = 1,
                            NgayDuyet = new DateTime(2026, 4, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            NgayLamViec = new DateOnly(2026, 4, 24),
                            NgayTao = new DateTime(2026, 4, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            NguonTaoCa = "TuDong",
                            SoSlotDaDat = 0,
                            SoSlotToiDa = 12,
                            ThoiGianSlot = 20,
                            TrangThaiDuyet = "DaDuyet"
                        },
                        new
                        {
                            IdCaLamViec = 3003,
                            GioBatDau = new TimeOnly(7, 0, 0),
                            GioKetThuc = new TimeOnly(12, 0, 0),
                            IdAdminDuyet = 2004,
                            IdBacSi = 2001,
                            IdChuyenKhoa = 1,
                            IdDinhNghiaCa = 1,
                            IdPhong = 1,
                            NgayDuyet = new DateTime(2026, 4, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            NgayLamViec = new DateOnly(2026, 4, 30),
                            NgayTao = new DateTime(2026, 4, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            NguonTaoCa = "TuDong",
                            SoSlotDaDat = 0,
                            SoSlotToiDa = 15,
                            ThoiGianSlot = 20,
                            TrangThaiDuyet = "DaDuyet"
                        });
                });

            modelBuilder.Entity("ClinicBooking.Domain.Entities.ChuyenKhoa", b =>
                {
                    b.Property<int>("IdChuyenKhoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdChuyenKhoa"));

                    b.Property<TimeOnly?>("GioDongDatLich")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("GioMoDatLich")
                        .HasColumnType("time");

                    b.Property<bool>("HienThi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenChuyenKhoa")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ThoiGianSlotMacDinh")
                        .HasColumnType("int");

                    b.HasKey("IdChuyenKhoa");

                    b.HasIndex("TenChuyenKhoa")
                        .IsUnique();

                    b.ToTable("ChuyenKhoa");

                    b.HasData(
                        new
                        {
                            IdChuyenKhoa = 1,
                            GioDongDatLich = new TimeOnly(17, 0, 0),
                            GioMoDatLich = new TimeOnly(7, 0, 0),
                            HienThi = true,
                            MoTa = "Khám và điều trị các bệnh lý về tim và mạch máu",
                            TenChuyenKhoa = "Tim Mạch",
                            ThoiGianSlotMacDinh = 20
                        },
                        new
                        {
                            IdChuyenKhoa = 2,
                            GioDongDatLich = new TimeOnly(17, 0, 0),
                            GioMoDatLich = new TimeOnly(7, 0, 0),
                            HienThi = true,
                            MoTa = "Khám và điều trị cho trẻ em dưới 16 tuổi",
                            TenChuyenKhoa = "Nhi Khoa",
                            ThoiGianSlotMacDinh = 15
                        },
                        new
                        {
                            IdChuyenKhoa = 3,
                            GioDongDatLich = new TimeOnly(17, 0, 0),
                            GioMoDatLich = new TimeOnly(7, 0, 0),
                            HienThi = true,
                            MoTa = "Khám tổng quát các bệnh lý nội khoa",
                            TenChuyenKhoa = "Nội Tổng Quát",
                            ThoiGianSlotMacDinh = 20
                        },
                        new
                        {
                            IdChuyenKhoa = 4,
                            GioDongDatLich = new TimeOnly(17, 0, 0),
                            GioMoDatLich = new TimeOnly(7, 0, 0),
                            HienThi = true,
                            MoTa = "Khám và điều trị các bệnh lý ngoại khoa",
                            TenChuyenKhoa = "Ngoại Tổng Quát",
                            ThoiGianSlotMacDinh = 30
                        },
                        new
                        {
                            IdChuyenKhoa = 5,
                            GioDongDatLich = new TimeOnly(17, 0, 0),
                            GioMoDatLich = new TimeOnly(7, 0, 0),
                            HienThi = true,
                            MoTa = "Khám và điều trị các bệnh lý tai, mũi, họng",
                            TenChuyenKhoa = "Tai Mũi Họng",
                            ThoiGianSlotMacDinh = 15
                        },
                        new
                        {
                            IdChuyenKhoa = 6,
                            GioDongDatLich = new TimeOnly(17, 0, 0),
                            GioMoDatLich = new TimeOnly(7, 0, 0),
                            HienThi = true,
                            MoTa = "Khám và điều trị các bệnh lý về da",
                            TenChuyenKhoa = "Da Liễu",
                            ThoiGianSlotMacDinh = 20
                        });
                });

            modelBuilder.Entity("ClinicBooking.Domain.Entities.DichVu", b =>
                {
                    b.Property<int>("IdDichVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDichVu"));

                    b.Property<bool>("HienThi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("IdChuyenKhoa")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ThoiGianUocTinh")
                        .HasColumnType("int");

                    b.HasKey("IdDichVu");

                    b.HasIndex("IdChuyenKhoa");

                    b.ToTable("DichVu");

                    b.HasData(
                        new
                        {
                            IdDichVu = 1,
                            HienThi = true,
                            IdChuyenKhoa = 1,
                            MoTa = "Khám lâm sàng tim mạch tổng quát",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TenDichVu = "Khám Tim Mạch Tổng Quát",
                            ThoiGianUocTinh = 20
                        },
                        new
                        {
                            IdDichVu = 2,
                            HienThi = true,
                            IdChuyenKhoa = 1,
                            MoTa = "Đo điện tim 12 chuyển đạo",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TenDichVu = "Điện Tim (ECG)",
                            ThoiGianUocTinh = 15
                        },
                        new
                        {
                            IdDichVu = 3,
                            HienThi = true,
                            IdChuyenKhoa = 1,
                            MoTa = "Siêu âm tim qua thành ngực",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TenDichVu = "Siêu Âm Tim",
                            ThoiGianUocTinh = 30
                        },
                        new
                        {
                            IdDichVu = 4,
                            HienThi = true,
                            IdChuyenKhoa = 2,
                            MoTa = "Khám tổng quát cho trẻ em",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TenDichVu = "Khám Nhi Tổng Quát",
                            ThoiGianUocTinh = 15
                        },
                        new
                        {
                            IdDichVu = 5,
                            HienThi = true,
                            IdChuyenKhoa = 2,
                            MoTa = "Tiêm vaccine theo lịch",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TenDichVu = "Tiêm Chủng",
                            ThoiGianUocTinh = 10
                        },
                        new
                        {
                            IdDichVu = 6,
                            HienThi = true,
                            IdChuyenKhoa = 3,
                            MoTa = "Khám tổng quát các bệnh lý nội khoa",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TenDichVu = "Khám Nội Tổng Quát",
                            ThoiGianUocTinh = 20
                        },
                        new
                        {
                            IdDichVu = 7,
                            HienThi = true,
                            IdChuyenKhoa = 4,
                            MoTa = "Khám lâm sàng ngoại khoa",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TenDichVu = "Khám Ngoại Tổng Quát",
                            ThoiGianUocTinh = 20
                        },
                        new
                        {
                            IdDichVu = 8,
                            HienThi = true,
                            IdChuyenKhoa = 4,
                            MoTa = "Tiểu phẫu các ca đơn giản",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TenDichVu = "Tiểu Phẫu",
                            ThoiGianUocTinh = 45
                        },
                        new
                        {
                            IdDichVu = 9,
                            HienThi = true,
                            IdChuyenKhoa = 5,
                            MoTa = "Khám lâm sàng tai, mũi, họng",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TenDichVu = "Khám Tai Mũi Họng",
                            ThoiGianUocTinh = 15
                        },
                        new
                        {
                            IdDichVu = 10,
                            HienThi = true,
                            IdChuyenKhoa = 5,
                            MoTa = "Nội soi chẩn đoán tai, mũi, họng",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TenDichVu = "Nội Soi Tai Mũi Họng",
                            ThoiGianUocTinh = 30
                        },
                        new
                        {
                            IdDichVu = 11,
                            HienThi = true,
                            IdChuyenKhoa = 6,
                            MoTa = "Khám các bệnh lý về da",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TenDichVu = "Khám Da Liễu",
                            ThoiGianUocTinh = 20
                        },
                        new
                        {
                            IdDichVu = 12,
                            HienThi = true,
                            IdChuyenKhoa = 6,
                            MoTa = "Soi da chẩn đoán bằng dermoscope",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TenDichVu = "Soi Da Bằng Dermoscope",
                            ThoiGianUocTinh = 20
                        });
                });

            modelBuilder.Entity("ClinicBooking.Domain.Entities.DinhNghiaCa", b =>
                {
                    b.Property<int>("IdDinhNghiaCa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDinhNghiaCa"));

                    b.Property<TimeOnly>("GioBatDauMacDinh")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("GioKetThucMacDinh")
                        .HasColumnType("time");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenCa")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("IdDinhNghiaCa");

                    b.HasIndex("TenCa")
                        .IsUnique();

                    b.ToTable("DinhNghiaCa");

                    b.HasData(
                        new
                        {
                            IdDinhNghiaCa = 1,
                            GioBatDauMacDinh = new TimeOnly(7, 0, 0),
                            GioKetThucMacDinh = new TimeOnly(12, 0, 0),
                            MoTa = "Ca sáng: 07:00 - 12:00",
                            TenCa = "sang",
                            TrangThai = true
                        },
                        new
                        {
                            IdDinhNghiaCa = 2,
                            GioBatDauMacDinh = new TimeOnly(13, 0, 0),
                            GioKetThucMacDinh = new TimeOnly(17, 0, 0),
                            MoTa = "Ca chiều: 13:00 - 17:00",
                            TenCa = "chieu",
                            TrangThai = true
                        },
                        new
                        {
                            IdDinhNghiaCa = 3,
                            GioBatDauMacDinh = new TimeOnly(17, 0, 0),
                            GioKetThucMacDinh = new TimeOnly(21, 0, 0),
                            MoTa = "Ca tối: 17:00 - 21:00",
                            TenCa = "toi",
                            TrangThai = true
                        },
                        new
                        {
                            IdDinhNghiaCa = 4,
                            GioBatDauMacDinh = new TimeOnly(7, 0, 0),
                            GioKetThucMacDinh = new TimeOnly(17, 0, 0),
                            MoTa = "Ca gộp sáng + chiều: 07:00 - 17:00",
                            TenCa = "sang_chieu",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("ClinicBooking.Domain.Entities.DonNghiPhep", b =>
                {
                    b.Property<int>("IdDonNghiPhep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDonNghiPhep"));

                    b.Property<int>("IdBacSi")
                        .HasColumnType("int");

                    b.Property<int>("IdCaLamViec")
                        .HasColumnType("int");

                    b.Property<int?>("IdNguoiDuyet")
                        .HasColumnType("int");

                    b.Property<string>("LoaiNghiPhep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LyDoTuChoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayGuiDon")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXuLy")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThaiDuyet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDonNghiPhep");

                    b.HasIndex("IdBacSi");

                    b.HasIndex("IdCaLamViec");

                    b.HasIndex("IdNguoiDuyet");

                    b.ToTable("DonNghiPhep");
                });

            modelBuilder.Entity("ClinicBooking.Domain.Entities.GiuCho", b =>
                {
                    b.Property<int>("IdGiuCho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGiuCho"));

                    b.Property<bool>("DaGiaiPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("GioHetHan")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdBenhNhan")
                        .HasColumnType("int");

                    b.Property<int>("IdCaLamViec")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoSlot")
                        .HasColumnType("int");

                    b.HasKey("IdGiuCho");

                    b.HasIndex("IdBenhNhan");

                    b.HasIndex("IdCaLamViec", "DaGiaiPhong", "GioHetHan");

                    b.ToTable("GiuCho");
                });

            modelBuilder.Entity("ClinicBooking.Domain.Entities.HangCho", b =>
                {
                    b.Property<int>("IdHangCho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHangCho"));

                    b.Property<int>("IdCaLamViec")
                        .HasColumnType("int");

                    b.Property<int>("IdLichHen")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCheckIn")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoThuTu")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdHangCho");

                    b.HasIndex("IdLichHen")
                        .IsUnique();

                    b.HasIndex("IdCaLamViec", "SoThuTu")
                        .IsUnique();

                    b.HasIndex("IdCaLamViec", "TrangThai", "SoThuTu");

                    b.ToTable("HangCho");

                    b.HasData(
                        new
                        {
                            IdHangCho = 5001,
                            IdCaLamViec = 3001,
                            IdLichHen = 4001,
                            NgayCheckIn = new DateTime(2026, 4, 22, 22, 0, 0, 0, DateTimeKind.Utc),
                            SoThuTu = 1,
                            TrangThai = "ChoKham"
                        });
                });

            modelBuilder.Entity("ClinicBooking.Domain.Entities.HoSoKham", b =>
                {
                    b.Property<int>("IdHoSoKham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHoSoKham"));

                    b.Property<string>("ChanDoan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdBacSi")
                        .HasColumnType("int");

                    b.Property<int>("IdLichHen")
                        .HasColumnType("int");

                    b.Property<string>("KetQuaKham")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayKham")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.HasKey("IdHoSoKham");

                    b.HasIndex("IdBacSi");

                    b.HasIndex("IdLichHen")
                        .IsUnique();

                    b.ToTable("HoSoKham");
                });

            modelBuilder.Entity("ClinicBooking.Domain.Entities.LeTan", b =>
                {
                    b.Property<int>("IdLeTan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLeTan"));

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdTaiKhoan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.HasKey("IdLeTan");

                    b.HasIndex("IdTaiKhoan")
                        .IsUnique();

                    b.ToTable("LeTan");
                });

            modelBuilder.Entity("ClinicBooking.Domain.Entities.LichHen", b =>
                {
                    b.Property<int>("IdLichHen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLichHen"));

                    b.Property<string>("BacSiMongMuonNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhThucDat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdBacSiMongMuon")
                        .HasColumnType("int");

                    b.Property<int>("IdBenhNhan")
                        .HasColumnType("int");

                    b.Property<int>("IdCaLamViec")
                        .HasColumnType("int");

                    b.Property<int>("IdDichVu")
                        .HasColumnType("int");

                    b.Property<string>("MaLichHen")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SoSlot")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TrieuChung")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdLichHen");

                    b.HasIndex("IdBacSiMongMuon");

                    b.HasIndex("IdDichVu");

                    b.HasIndex("MaLichHen")
                        .IsUnique();

                    b.HasIndex("IdBenhNhan", "TrangThai");

                    b.HasIndex("IdCaLamViec", "SoSlot")
                        .IsUnique();

                    b.HasIndex("IdCaLamViec", "TrangThai");

                    b.ToTable("LichHen");

                    b.HasData(
                        new
                        {
                            IdLichHen = 4001,
                            HinhThucDat = "TrucTuyen",
                            IdBenhNhan = 2001,
                            IdCaLamViec = 3001,
                            IdDichVu = 1,
                            MaLichHen = "LH-20260424-001",
                            NgayTao = new DateTime(2026, 4, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            RowVersion = new byte[0],
                            SoSlot = 1,
                            TrangThai = "DaXacNhan",
                            TrieuChung = "Dau nguc nhe"
                        },
                        new
                        {
                            IdLichHen = 4002,
                            HinhThucDat = "TrucTuyen",
                            IdBenhNhan = 2001,
                            IdCaLamViec = 3001,
                            IdDichVu = 2,
                            MaLichHen = "LH-20260424-002",
                            NgayTao = new DateTime(2026, 4, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            RowVersion = new byte[0],
                            SoSlot = 2,
                            TrangThai = "ChoXacNhan"
                        });
                });

            modelBuilder.Entity("ClinicBooking.Domain.Entities.LichNoiTru", b =>
                {
                    b.Property<int>("IdLichNoiTru")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLichNoiTru"));

                    b.Property<int>("IdBacSi")
                        .HasColumnType("int");

                    b.Property<int>("IdDinhNghiaCa")
                        .HasColumnType("int");

                    b.Property<int>("IdPhong")
                        .HasColumnType("int");

                    b.Property<DateOnly>("NgayApDung")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NgayKetThuc")
                        .HasColumnType("date");

                    b.Property<int>("NgayTrongTuan")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("IdLichNoiTru");

                    b.HasIndex("IdBacSi");

                    b.HasIndex("IdDinhNghiaCa");

                    b.HasIndex("IdPhong");

                    b.ToTable("LichNoiTru");
                });

            modelBuilder.Entity("ClinicBooking.Domain.Entities.LichSuLichHen", b =>
                {
                    b.Property<int>("IdLichSu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLichSu"));

                    b.Property<bool>("DanhDauHuyMuon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdLichHen")
                        .HasColumnType("int");

                    b.Property<int?>("IdLichHenTruoc")
                        .HasColumnType("int");

                    b.Property<int?>("IdNguoiThucHien")
                        .HasColumnType("int");

                    b.Property<string>("LyDo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.HasKey("IdLichSu");

                    b.HasIndex("IdLichHen");

                    b.HasIndex("IdLichHenTruoc");

                    b.HasIndex("IdNguoiThucHien");

                    b.ToTable("LichSuLichHen");

                    b.HasData(
                        new
                        {
                            IdLichSu = 6001,
                            DanhDauHuyMuon = false,
                            HanhDong = "DatMoi",
                            IdLichHen = 4001,
                            NgayTao = new DateTime(2026, 4, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            IdLichSu = 6002,
                            DanhDauHuyMuon = false,
                            HanhDong = "XacNhan",
                            IdLichHen = 4001,
                            IdNguoiThucHien = 2004,
                            LyDo = "Admin xac nhan",
                            NgayTao = new DateTime(2026, 4, 23, 0, 5, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("ClinicBooking.Domain.Entities.MauThongBao", b =>
                {
                    b.Property<int>("IdMau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMau"));

                    b.Property<string>("KenhGui")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiThongBao")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NoiDungMau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDeMau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMau");

                    b.HasIndex("LoaiThongBao")
                        .IsUnique();

                    b.ToTable("MauThongBao");

                    b.HasData(
                        new
                        {
                            IdMau = 1,
                            KenhGui = "Email",
                            LoaiThongBao = "XacNhanLich",
                            NoiDungMau = "Xin chào {ten_benh_nhan}, lịch hẹn của bạn mã {ma_lich_hen} vào ngày {ngay_kham} đã được xác nhận. Vui lòng đến trước giờ hẹn 15 phút.",
                            TieuDeMau = "Xác nhận lịch hẹn {ma_lich_hen}"
                        },
                        new
                        {
                            IdMau = 2,
                            KenhGui = "Email",
                            LoaiThongBao = "Nhac1Ngay",
                            NoiDungMau = "Xin chào {ten_benh_nhan}, bạn có lịch hẹn khám vào ngày mai {ngay_kham} lúc {gio_kham}. Mã lịch hẹn: {ma_lich_hen}.",
                            TieuDeMau = "Nhắc lịch khám ngày mai"
                        },
                        new
                        {
                            IdMau = 3,
                            KenhGui = "Sms",
                            LoaiThongBao = "Nhac2Gio",
                            NoiDungMau = "{ten_benh_nhan}, bạn có lịch khám lúc {gio_kham} hôm nay. Mã: {ma_lich_hen}.",
                            TieuDeMau = "Nhắc lịch khám 2 giờ tới"
                        },
                        new
                        {
                            IdMau = 4,
                            KenhGui = "Email",
                            LoaiThongBao = "HuyLich",
                            NoiDungMau = "Xin chào {ten_benh_nhan}, lịch hẹn {ma_lich_hen} vào ngày {ngay_kham} đã được hủy. Lý do: {ly_do}.",
                            TieuDeMau = "Hủy lịch hẹn {ma_lich_hen}"
                        },
                        new
                        {
                            IdMau = 5,
                            KenhGui = "TrongApp",
                            LoaiThongBao = "CheckIn",
                            NoiDungMau = "Bạn đã check-in thành công. Số thứ tự của bạn là {so_thu_tu}. Vui lòng chờ gọi tên.",
                            TieuDeMau = "Check-in thành công"
                        },
                        new
                        {
                            IdMau = 6,
                            KenhGui = "TrongApp",
                            LoaiThongBao = "DuyetCa",
                            NoiDungMau = "Ca làm việc ngày {ngay_lam_viec} của bạn đã được admin duyệt.",
                            TieuDeMau = "Ca làm việc đã được duyệt"
                        },
                        new
                        {
                            IdMau = 7,
                            KenhGui = "TrongApp",
                            LoaiThongBao = "TuChoiCa",
                            NoiDungMau = "Ca làm việc ngày {ngay_lam_viec} của bạn đã bị admin từ chối. Lý do: {ly_do}.",
                            TieuDeMau = "Ca làm việc bị từ chối"
                        });
                });

            modelBuilder.Entity("ClinicBooking.Domain.Entities.OtpLog", b =>
                {
                    b.Property<int>("IdOtpLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOtpLog"));

                    b.Property<bool>("DaSuDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("DiaChiIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GioHetHan")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdPhien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdTaiKhoan")
                        .HasColumnType("int");

                    b.Property<string>("MaOtp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MucDich")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLanThu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("IdOtpLog");

                    b.HasIndex("IdTaiKhoan", "MucDich", "NgayTao");

                    b.ToTable("OtpLog");
                });

            modelBuilder.Entity("ClinicBooking.Domain.Entities.Phong", b =>
                {
                    b.Property<int>("IdPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPhong"));

                    b.Property<string>("MaPhong")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("SucChua")
                        .HasColumnType("int");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangBi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("IdPhong");

                    b.HasIndex("MaPhong")
                        .IsUnique();

                    b.ToTable("Phong");

                    b.HasData(
                        new
                        {
                            IdPhong = 1,
                            MaPhong = "P101",
                            SucChua = 10,
                            TenPhong = "Phòng Khám 101",
                            TrangBi = "Giường khám, máy đo huyết áp, ống nghe",
                            TrangThai = true
                        },
                        new
                        {
                            IdPhong = 2,
                            MaPhong = "P102",
                            SucChua = 10,
                            TenPhong = "Phòng Khám 102",
                            TrangBi = "Giường khám, máy đo huyết áp, ống nghe",
                            TrangThai = true
                        },
                        new
                        {
                            IdPhong = 3,
                            MaPhong = "P201",
                            SucChua = 8,
                            TenPhong = "Phòng Khám Nhi 201",
                            TrangBi = "Giường khám trẻ em, cân đo chuyên dụng",
                            TrangThai = true
                        },
                        new
                        {
                            IdPhong = 4,
                            MaPhong = "P202",
                            SucChua = 8,
                            TenPhong = "Phòng Khám 202",
                            TrangBi = "Giường khám, máy đo huyết áp",
                            TrangThai = true
                        },
                        new
                        {
                            IdPhong = 5,
                            MaPhong = "P301",
                            SucChua = 5,
                            TenPhong = "Phòng Siêu Âm",
                            TrangBi = "Máy siêu âm 4D",
                            TrangThai = true
                        },
                        new
                        {
                            IdPhong = 6,
                            MaPhong = "P302",
                            SucChua = 5,
                            TenPhong = "Phòng X-Quang",
                            TrangBi = "Máy X-quang kỹ thuật số",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("ClinicBooking.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("IdRefreshToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRefreshToken"));

                    b.Property<bool>("DaThuHoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("HetHan")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdTaiKhoan")
                        .HasColumnType("int");

                    b.Property<string>("LyDoThuHoi")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayThuHoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("ThayTheBangToken")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("IdRefreshToken");

                    b.HasIndex("IdTaiKhoan");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("ClinicBooking.Domain.Entities.TaiKhoan", b =>
                {
                    b.Property<int>("IdTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTaiKhoan"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("LanDangNhapCuoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTaiKhoan");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SoDienThoai")
                        .IsUnique();

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("TaiKhoan");

                    b.HasData(
                        new
                        {
                            IdTaiKhoan = 1,
                            Email = "admin@phongkham.local",
                            MatKhau = "$2a$11$GiaLapHashThayDoiTruocKhiDeployProdXXXXXXXXXXXXXXXXXXXX",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SoDienThoai = "0900000000",
                            TenDangNhap = "admin",
                            TrangThai = true,
                            VaiTro = "Admin"
                        },
                        new
                        {
                            IdTaiKhoan = 2001,
                            Email = "patient@test.vn",
                            MatKhau = "$2a$11$encrypted_password",
                            NgayTao = new DateTime(2026, 4, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            SoDienThoai = "0912345678",
                            TenDangNhap = "patient001",
                            TrangThai = true,
                            VaiTro = "BenhNhan"
                        },
                        new
                        {
                            IdTaiKhoan = 2002,
                            Email = "doctor@test.vn",
                            MatKhau = "$2a$11$encrypted_password",
                            NgayTao = new DateTime(2026, 4, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            SoDienThoai = "0987654321",
                            TenDangNhap = "doctor001",
                            TrangThai = true,
                            VaiTro = "BacSi"
                        },
                        new
                        {
                            IdTaiKhoan = 2003,
                            Email = "receptionist@test.vn",
                            MatKhau = "$2a$11$encrypted_password",
                            NgayTao = new DateTime(2026, 4, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            SoDienThoai = "0911111111",
                            TenDangNhap = "receptionist001",
                            TrangThai = true,
                            VaiTro = "LeTan"
                        },
                        new
                        {
                            IdTaiKhoan = 2004,
                            Email = "admin@test.vn",
                            MatKhau = "$2a$11$encrypted_password",
                            NgayTao = new DateTime(2026, 4, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            SoDienThoai = "0988888888",
                            TenDangNhap = "admin001",
                            TrangThai = true,
                            VaiTro = "Admin"
                        });
                });

            modelBuilder.Entity("ClinicBooking.Domain.Entities.ThongBao", b =>
                {
                    b.Property<int>("IdThongBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdThongBao"));

                    b.Property<bool>("DaDoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("IdMau")
                        .HasColumnType("int");

                    b.Property<int>("IdTaiKhoan")
                        .HasColumnType("int");

                    b.Property<int?>("IdThamChieu")
                        .HasColumnType("int");

                    b.Property<string>("KenhGui")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiThamChieu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayGui")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdThongBao");

                    b.HasIndex("IdMau");

                    b.HasIndex("IdTaiKhoan");

                    b.ToTable("ThongBao");
                });

            modelBuilder.Entity("ClinicBooking.Domain.Entities.Thuoc", b =>
                {
                    b.Property<int>("IdThuoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdThuoc"));

                    b.Property<string>("DonVi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoatChat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenThuoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdThuoc");

                    b.HasIndex("TenThuoc")
                        .IsUnique();

                    b.ToTable("Thuoc");

                    b.HasData(
                        new
                        {
                            IdThuoc = 1,
                            DonVi = "Viên",
                            GhiChu = "Giảm đau, hạ sốt",
                            HoatChat = "Paracetamol",
                            TenThuoc = "Paracetamol 500mg"
                        },
                        new
                        {
                            IdThuoc = 2,
                            DonVi = "Viên",
                            GhiChu = "Kháng sinh nhóm Beta-lactam",
                            HoatChat = "Amoxicillin",
                            TenThuoc = "Amoxicillin 500mg"
                        },
                        new
                        {
                            IdThuoc = 3,
                            DonVi = "Viên",
                            GhiChu = "Kháng viêm, giảm đau NSAID",
                            HoatChat = "Ibuprofen",
                            TenThuoc = "Ibuprofen 400mg"
                        },
                        new
                        {
                            IdThuoc = 4,
                            DonVi = "Viên",
                            GhiChu = "Ức chế bơm proton, điều trị viêm loét dạ dày",
                            HoatChat = "Omeprazole",
                            TenThuoc = "Omeprazole 20mg"
                        },
                        new
                        {
                            IdThuoc = 5,
                            DonVi = "Viên",
                            GhiChu = "Kháng histamin H1, dị ứng",
                            HoatChat = "Cetirizine",
                            TenThuoc = "Cetirizine 10mg"
                        },
                        new
                        {
                            IdThuoc = 6,
                            DonVi = "Viên",
                            GhiChu = "Bổ sung vitamin C",
                            HoatChat = "Ascorbic Acid",
                            TenThuoc = "Vitamin C 500mg"
                        },
                        new
                        {
                            IdThuoc = 7,
                            DonVi = "Chai",
                            GhiChu = "Rửa mắt, rửa mũi",
                            HoatChat = "NaCl 0.9%",
                            TenThuoc = "Nước Muối Sinh Lý 0.9%"
                        },
                        new
                        {
                            IdThuoc = 8,
                            DonVi = "Viên",
                            GhiChu = "Kháng histamin H1 thế hệ 2",
                            HoatChat = "Loratadine",
                            TenThuoc = "Loratadine 10mg"
                        });
                });

            modelBuilder.Entity("ClinicBooking.Domain.Entities.ToaThuoc", b =>
                {
                    b.Property<int>("IdToaThuoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdToaThuoc"));

                    b.Property<string>("CachDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdHoSoKham")
                        .HasColumnType("int");

                    b.Property<int>("IdThuoc")
                        .HasColumnType("int");

                    b.Property<string>("LieuLuong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoNgayDung")
                        .HasColumnType("int");

                    b.HasKey("IdToaThuoc");

                    b.HasIndex("IdHoSoKham");

                    b.HasIndex("IdThuoc");

                    b.ToTable("ToaThuoc");
                });

            modelBuilder.Entity("ClinicBooking.Domain.Entities.BacSi", b =>
                {
                    b.HasOne("ClinicBooking.Domain.Entities.ChuyenKhoa", "ChuyenKhoa")
                        .WithMany("DanhSachBacSi")
                        .HasForeignKey("IdChuyenKhoa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicBooking.Domain.Entities.TaiKhoan", "TaiKhoan")
                        .WithOne("BacSi")
                        .HasForeignKey("ClinicBooking.Domain.Entities.BacSi", "IdTaiKhoan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChuyenKhoa");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("ClinicBooking.Domain.Entities.BenhNhan", b =>
                {
                    b.HasOne("ClinicBooking.Domain.Entities.TaiKhoan", "TaiKhoan")
                        .WithOne("BenhNhan")
                        .HasForeignKey("ClinicBooking.Domain.Entities.BenhNhan", "IdTaiKhoan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("ClinicBooking.Domain.Entities.CaLamViec", b =>
                {
                    b.HasOne("ClinicBooking.Domain.Entities.TaiKhoan", "AdminDuyet")
                        .WithMany()
                        .HasForeignKey("IdAdminDuyet")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClinicBooking.Domain.Entities.BacSi", "BacSi")
                        .WithMany("DanhSachCaLamViec")
                        .HasForeignKey("IdBacSi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicBooking.Domain.Entities.BacSi", "BacSiYeuCau")
                        .WithMany()
                        .HasForeignKey("IdBacSiYeuCau")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClinicBooking.Domain.Entities.ChuyenKhoa", "ChuyenKhoa")
                        .WithMany("DanhSachCaLamViec")
                        .HasForeignKey("IdChuyenKhoa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicBooking.Domain.Entities.DinhNghiaCa", "DinhNghiaCa")
                        .WithMany("DanhSachCaLamViec")
                        .HasForeignKey("IdDinhNghiaCa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicBooking.Domain.Entities.Phong", "Phong")
                        .WithMany("DanhSachCaLamViec")
                        .HasForeignKey("IdPhong")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdminDuyet");

                    b.Navigation("BacSi");

                    b.Navigation("BacSiYeuCau");

                    b.Navigation("ChuyenKhoa");

                    b.Navigation("DinhNghiaCa");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("ClinicBooking.Domain.Entities.DichVu", b =>
                {
                    b.HasOne("ClinicBooking.Domain.Entities.ChuyenKhoa", "ChuyenKhoa")
                        .WithMany("DanhSachDichVu")
                        .HasForeignKey("IdChuyenKhoa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChuyenKhoa");
                });

            modelBuilder.Entity("ClinicBooking.Domain.Entities.DonNghiPhep", b =>
                {
                    b.HasOne("ClinicBooking.Domain.Entities.BacSi", "BacSi")
                        .WithMany("DanhSachDonNghiPhep")
                        .HasForeignKey("IdBacSi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicBooking.Domain.Entities.CaLamViec", "CaLamViec")
                        .WithMany("DanhSachDonNghiPhep")
                        .HasForeignKey("IdCaLamViec")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicBooking.Domain.Entities.TaiKhoan", "NguoiDuyet")
                        .WithMany()
                        .HasForeignKey("IdNguoiDuyet")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BacSi");

                    b.Navigation("CaLamViec");

                    b.Navigation("NguoiDuyet");
                });

            modelBuilder.Entity("ClinicBooking.Domain.Entities.GiuCho", b =>
                {
                    b.HasOne("ClinicBooking.Domain.Entities.BenhNhan", "BenhNhan")
                        .WithMany("DanhSachGiuCho")
                        .HasForeignKey("IdBenhNhan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicBooking.Domain.Entities.CaLamViec", "CaLamViec")
                        .WithMany("DanhSachGiuCho")
                        .HasForeignKey("IdCaLamViec")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BenhNhan");

                    b.Navigation("CaLamViec");
                });

            modelBuilder.Entity("ClinicBooking.Domain.Entities.HangCho", b =>
                {
                    b.HasOne("ClinicBooking.Domain.Entities.CaLamViec", "CaLamViec")
                        .WithMany("DanhSachHangCho")
                        .HasForeignKey("IdCaLamViec")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicBooking.Domain.Entities.LichHen", "LichHen")
                        .WithOne("HangCho")
                        .HasForeignKey("ClinicBooking.Domain.Entities.HangCho", "IdLichHen")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CaLamViec");

                    b.Navigation("LichHen");
                });

            modelBuilder.Entity("ClinicBooking.Domain.Entities.HoSoKham", b =>
                {
                    b.HasOne("ClinicBooking.Domain.Entities.BacSi", "BacSi")
                        .WithMany("DanhSachHoSoKham")
                        .HasForeignKey("IdBacSi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicBooking.Domain.Entities.LichHen", "LichHen")
                        .WithOne("HoSoKham")
                        .HasForeignKey("ClinicBooking.Domain.Entities.HoSoKham", "IdLichHen")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BacSi");

                    b.Navigation("LichHen");
                });

            modelBuilder.Entity("ClinicBooking.Domain.Entities.LeTan", b =>
                {
                    b.HasOne("ClinicBooking.Domain.Entities.TaiKhoan", "TaiKhoan")
                        .WithOne("LeTan")
                        .HasForeignKey("ClinicBooking.Domain.Entities.LeTan", "IdTaiKhoan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("ClinicBooking.Domain.Entities.LichHen", b =>
                {
                    b.HasOne("ClinicBooking.Domain.Entities.BacSi", "BacSiMongMuon")
                        .WithMany()
                        .HasForeignKey("IdBacSiMongMuon")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClinicBooking.Domain.Entities.BenhNhan", "BenhNhan")
                        .WithMany("DanhSachLichHen")
                        .HasForeignKey("IdBenhNhan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicBooking.Domain.Entities.CaLamViec", "CaLamViec")
                        .WithMany("DanhSachLichHen")
                        .HasForeignKey("IdCaLamViec")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicBooking.Domain.Entities.DichVu", "DichVu")
                        .WithMany("DanhSachLichHen")
                        .HasForeignKey("IdDichVu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BacSiMongMuon");

                    b.Navigation("BenhNhan");

                    b.Navigation("CaLamViec");

                    b.Navigation("DichVu");
                });

            modelBuilder.Entity("ClinicBooking.Domain.Entities.LichNoiTru", b =>
                {
                    b.HasOne("ClinicBooking.Domain.Entities.BacSi", "BacSi")
                        .WithMany("DanhSachLichNoiTru")
                        .HasForeignKey("IdBacSi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicBooking.Domain.Entities.DinhNghiaCa", "DinhNghiaCa")
                        .WithMany("DanhSachLichNoiTru")
                        .HasForeignKey("IdDinhNghiaCa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicBooking.Domain.Entities.Phong", "Phong")
                        .WithMany("DanhSachLichNoiTru")
                        .HasForeignKey("IdPhong")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BacSi");

                    b.Navigation("DinhNghiaCa");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("ClinicBooking.Domain.Entities.LichSuLichHen", b =>
                {
                    b.HasOne("ClinicBooking.Domain.Entities.LichHen", "LichHen")
                        .WithMany("DanhSachLichSu")
                        .HasForeignKey("IdLichHen")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicBooking.Domain.Entities.LichHen", "LichHenTruoc")
                        .WithMany()
                        .HasForeignKey("IdLichHenTruoc")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClinicBooking.Domain.Entities.TaiKhoan", "NguoiThucHien")
                        .WithMany()
                        .HasForeignKey("IdNguoiThucHien")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LichHen");

                    b.Navigation("LichHenTruoc");

                    b.Navigation("NguoiThucHien");
                });

            modelBuilder.Entity("ClinicBooking.Domain.Entities.OtpLog", b =>
                {
                    b.HasOne("ClinicBooking.Domain.Entities.TaiKhoan", "TaiKhoan")
                        .WithMany("DanhSachOtpLog")
                        .HasForeignKey("IdTaiKhoan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("ClinicBooking.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("ClinicBooking.Domain.Entities.TaiKhoan", "TaiKhoan")
                        .WithMany("DanhSachRefreshToken")
                        .HasForeignKey("IdTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("ClinicBooking.Domain.Entities.ThongBao", b =>
                {
                    b.HasOne("ClinicBooking.Domain.Entities.MauThongBao", "MauThongBao")
                        .WithMany("DanhSachThongBao")
                        .HasForeignKey("IdMau")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicBooking.Domain.Entities.TaiKhoan", "TaiKhoan")
                        .WithMany("DanhSachThongBao")
                        .HasForeignKey("IdTaiKhoan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MauThongBao");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("ClinicBooking.Domain.Entities.ToaThuoc", b =>
                {
                    b.HasOne("ClinicBooking.Domain.Entities.HoSoKham", "HoSoKham")
                        .WithMany("DanhSachToaThuoc")
                        .HasForeignKey("IdHoSoKham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicBooking.Domain.Entities.Thuoc", "Thuoc")
                        .WithMany("DanhSachToaThuoc")
                        .HasForeignKey("IdThuoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HoSoKham");

                    b.Navigation("Thuoc");
                });

            modelBuilder.Entity("ClinicBooking.Domain.Entities.BacSi", b =>
                {
                    b.Navigation("DanhSachCaLamViec");

                    b.Navigation("DanhSachDonNghiPhep");

                    b.Navigation("DanhSachHoSoKham");

                    b.Navigation("DanhSachLichNoiTru");
                });

            modelBuilder.Entity("ClinicBooking.Domain.Entities.BenhNhan", b =>
                {
                    b.Navigation("DanhSachGiuCho");

                    b.Navigation("DanhSachLichHen");
                });

            modelBuilder.Entity("ClinicBooking.Domain.Entities.CaLamViec", b =>
                {
                    b.Navigation("DanhSachDonNghiPhep");

                    b.Navigation("DanhSachGiuCho");

                    b.Navigation("DanhSachHangCho");

                    b.Navigation("DanhSachLichHen");
                });

            modelBuilder.Entity("ClinicBooking.Domain.Entities.ChuyenKhoa", b =>
                {
                    b.Navigation("DanhSachBacSi");

                    b.Navigation("DanhSachCaLamViec");

                    b.Navigation("DanhSachDichVu");
                });

            modelBuilder.Entity("ClinicBooking.Domain.Entities.DichVu", b =>
                {
                    b.Navigation("DanhSachLichHen");
                });

            modelBuilder.Entity("ClinicBooking.Domain.Entities.DinhNghiaCa", b =>
                {
                    b.Navigation("DanhSachCaLamViec");

                    b.Navigation("DanhSachLichNoiTru");
                });

            modelBuilder.Entity("ClinicBooking.Domain.Entities.HoSoKham", b =>
                {
                    b.Navigation("DanhSachToaThuoc");
                });

            modelBuilder.Entity("ClinicBooking.Domain.Entities.LichHen", b =>
                {
                    b.Navigation("DanhSachLichSu");

                    b.Navigation("HangCho");

                    b.Navigation("HoSoKham");
                });

            modelBuilder.Entity("ClinicBooking.Domain.Entities.MauThongBao", b =>
                {
                    b.Navigation("DanhSachThongBao");
                });

            modelBuilder.Entity("ClinicBooking.Domain.Entities.Phong", b =>
                {
                    b.Navigation("DanhSachCaLamViec");

                    b.Navigation("DanhSachLichNoiTru");
                });

            modelBuilder.Entity("ClinicBooking.Domain.Entities.TaiKhoan", b =>
                {
                    b.Navigation("BacSi");

                    b.Navigation("BenhNhan");

                    b.Navigation("DanhSachOtpLog");

                    b.Navigation("DanhSachRefreshToken");

                    b.Navigation("DanhSachThongBao");

                    b.Navigation("LeTan");
                });

            modelBuilder.Entity("ClinicBooking.Domain.Entities.Thuoc", b =>
                {
                    b.Navigation("DanhSachToaThuoc");
                });
#pragma warning restore 612, 618
        }
    }
}
